package videojuegos;

public enum TipoPlataforma {
	PC, PLAYSTATION_3, MACOS, IOS, ANDROID, LINUX, PLAYSTATION_4, NINTENDO_SWITCH, XBOX_360, XBOX_ONE, WII_U,  PLAYSTATION, PS_VITA, 
	GAME_BOY_ADVANCE, WEB, WII, PLAYSTATION_2, PSP, CLASSIC_MACINTOSH, XBOX, GAMECUBE, NINTENDO_3DS, NINTENDO_64, COMMODORE_AMIGA, NINTENDO_DSI,
	DREAMCAST, GAME_BOY_COLOR, SEGA_CD, GAME_BOY, NINTENDO_DS, SEGA_MASTER_SYSTEM, SEGA_SATURN, APPLE_II, GAME_GEAR, JAGUAR, SNES

}
