package videojuegos;

public enum TipoGenero {
	ACTION, CARD,  SHOOTER, PUZZLE, RPG, ADVENTURE, MASSIVELY_MULTIPLAYER, SPORTS, INDIE, PLATFORMER, STRATEGY, SIMULATION,
	FIGHTING, RACING, FAMILY, ARCADE, CASUAL, EDUCATIONAL, BOARD_GAMES, CREPPY

}
